### ISSUE TITLE
Fossil fuel should come before available rebates

### ISSUE THREAD

**Issue by silverliningco** [silverliningco/dcnebates-ng#10]
Some rebates only apply to a specific fossil fuel type (eg. natural gas, oil, propane).  In the current flow we ask for fossil fuel available at the home only after showing the available rebates, which does not make a lot of sense.  Consider moving the "fossil fuel" step before "available rebates" screen.

**Comment by esperanzaWG** [comment]
add '&fuelSource=' like parameter in the service
